# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

#development:
#  adapter: mysql
#  encoding: utf8
#  database: testapp_development
#  pool: 5
#  username: rails_user
#  password: rails_user

#test:
#  adapter: mysql
#  encoding: utf8
#  database: testapp_test
#  pool: 5
#  username: rails_user
#  password: rails_user

development:
  adapter: sqlite3
  encoding: utf8
  database: testapp_development
  pool: 5
  username: rails_user
  password: rails_user

test:
  adapter: sqlite3
  encoding: utf8
  database: testapp_test
  pool: 5
  username: rails_user
  password: rails_user

production:
  adapter: postgresql
  encoding: utf8
  database: dancef_ujkh67
  pool: 5
  username: dancef_ujkh67
  password: kR74Ner6tr

#production:
#  adapter: sqlite3
#  encoding: utf8
#  database: testapp_production
#  pool: 5
#  username: rails_user
#  password: rails_user