invalid_elements: "relative,script,mailto,href"
valid_elements: "em,li,ul,p,strong,ol,i,b,span,h1,h2,h3,h4,h5,h6,div"

#paste_text_linebreaktype: br

#force_p_newlines : false
#force_br_newlines : true
#convert_newlines_to_brs : false
#remove_linebreaks : false
forced_root_block : 'div'


force_br_newlines : true
force_p_newlines : false